# Generated by Django 3.2.10 on 2021-12-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hand', models.IntegerField(blank=True, default=False)),
                ('Card_Type', models.CharField(blank=True, default=False, max_length=20)),
                ('Card_Value_Type', models.CharField(blank=True, default=False, max_length=25)),
                ('Tricks', models.IntegerField(blank=True, default=False)),
                ('Vulnerable', models.BooleanField()),
            ],
        ),
    ]
