# Generated by Django 3.2.10 on 2021-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='Trick_Points',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='Tricks',
            field=models.CharField(blank=True, default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='Vulnerable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
